<section class="video-section">
    <h1>CALENDAR OF EVENTS 2025</h1>
    <div class="video-container">
        <iframe width="560"
            height="315"
            src="<?php echo htmlspecialchars($youtube_data['url']); ?>"
            title="<?php echo isset($youtube_data['title']) ? htmlspecialchars($youtube_data['title']) : 'Video Profil Tim'; ?>"
            frameborder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
            allowfullscreen>
        </iframe>
    </div>
</section>

<div class="profile-section">
    <h1>PROFIL PELIPUT PEMASARAN</h1>

    <div class="slider-container">
        <div class="arrow arrow-left" id="arrow-left">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                <path d="M15.41 7.41L14 6l-6 6 6 6 1.41-1.41L10.83 12z" />
            </svg>
        </div>

        <div class="profile-slider" id="profile-slider">
            <?php if (!empty($profiles)): ?>
                <?php foreach ($profiles as $profile): ?>
                    <div class="card">
                        <img src="/<?php echo htmlspecialchars($profile['pass_photo']); ?>"
                            alt="<?php echo htmlspecialchars($profile['full_name']); ?>"
                            class="pas-photo">
                        <div class="detail">
                            <?php if (!empty($profile['linkedin'])): ?>
                                <a href="<?php echo htmlspecialchars($profile['linkedin']); ?>"
                                    target="_blank" rel="noopener noreferrer">
                                    <img class="contact-profile"
                                        src="/assets/images/contacts/linkedin-rounded-svgrepo-com.png"
                                        alt="LinkedIn">
                                </a>
                            <?php endif; ?>

                            <?php if (!empty($profile['instagram'])): ?>
                                <a href="<?php echo htmlspecialchars($profile['instagram']); ?>"
                                    target="_blank" rel="noopener noreferrer">
                                    <img class="contact-profile"
                                        src="/assets/images/contacts/instagram-rounded-svgrepo-com.png"
                                        alt="Instagram">
                                </a>
                            <?php endif; ?>

                            <?php if (!empty($profile['facebook'])): ?>
                                <a href="<?php echo htmlspecialchars($profile['facebook']); ?>"
                                    target="_blank" rel="noopener noreferrer">
                                    <img class="contact-profile"
                                        src="/assets/images/contacts/facebook-rounded-svgrepo-com.png"
                                        alt="Facebook">
                                </a>
                            <?php endif; ?>

                            <?php if (!empty($profile['tiktok'])): ?>
                                <a class="tiktok" href="<?php echo htmlspecialchars($profile['tiktok']); ?>"
                                    target="_blank" rel="noopener noreferrer">
                                    <img class="contact-profile"
                                        src="/assets/images/contacts/brand-tiktok-sq-svgrepo-com.png"
                                        alt="TikTok">
                                </a>
                            <?php endif; ?>
                        </div>
                        <div class="info">
                            <h2><?php echo htmlspecialchars($profile['full_name']); ?></h2>
                            <p><?php echo htmlspecialchars($profile['position']); ?></p>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php else: ?>
                <!-- Fallback jika tidak ada data di database -->
                <div class="card">
                    <div class="info">
                        <h2>Tidak ada profil tersedia</h2>
                        <p>Silakan tambahkan profil melalui admin panel</p>
                    </div>
                </div>
            <?php endif; ?>
        </div>

        <div class="arrow arrow-right" id="arrow-right">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                <path d="M10 6L8.59 7.41 13.17 12l-4.58 4.59L10 18l6-6z" />
            </svg>
        </div>
    </div>

    <div class="slider-dots" id="slider-dots">
        <!-- Dots will be generated by JavaScript -->
    </div>
</div>