<?php
    $coe_image = null;
    if (!empty($coe_list) && isset($coe_list[0]['image'])) {
        $coe_image = $coe_list[0]['image'];
    }
?>

<section class="coe-section">
    <h1>CALENDAR OF EVENTS 2025</h1>
    <div class="coe-container">
        <?php if ($coe_image): ?>
            <img src="<?= BASEURL . '/' . htmlspecialchars($coe_image); ?>" 
                 alt="Calendar of Events 2025" 
                 class="coe-image">
        <?php else: ?>
            <div class="coe-placeholder">
                <i class="fas fa-calendar fa-3x"></i>
                <p>Calendar of Event belum tersedia</p>
            </div>
        <?php endif; ?>
    </div>
</section>

<div class="profile-section">
    <h1>PROFIL PELIPUT PEMASARAN</h1>

    <div class="slider-container">
        <div class="arrow arrow-left" id="arrow-left">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                <path d="M15.41 7.41L14 6l-6 6 6 6 1.41-1.41L10.83 12z" />
            </svg>
        </div>

        <div class="profile-slider" id="profile-slider">
            <?php if (!empty($profiles)): ?>
                <?php foreach ($profiles as $profile): ?>
                    <div class="card">
                        <img src="<?= BASEURL . '/' . htmlspecialchars($profile['pass_photo']); ?>"
                            alt="<?php echo htmlspecialchars($profile['full_name']); ?>"
                            class="pas-photo">
                        <div class="detail">
                            <?php if (!empty($profile['linkedin'])): ?>
                                <a href="<?php echo htmlspecialchars($profile['linkedin']); ?>"
                                    target="_blank" rel="noopener noreferrer">
                                    <img class="contact-profile"
                                        src="<?= BASEURL . '/img/contacts/linkedin-rounded-svgrepo-com.png' ?>"
                                        alt="LinkedIn">
                                </a>
                            <?php endif; ?>

                            <?php if (!empty($profile['instagram'])): ?>
                                <a href="<?php echo htmlspecialchars($profile['instagram']); ?>"
                                    target="_blank" rel="noopener noreferrer">
                                    <img class="contact-profile"
                                        src="<?= BASEURL . '/img/contacts/instagram-rounded-svgrepo-com.png' ?>"
                                        alt="Instagram">
                                </a>
                            <?php endif; ?>

                            <?php if (!empty($profile['facebook'])): ?>
                                <a href="<?php echo htmlspecialchars($profile['facebook']); ?>"
                                    target="_blank" rel="noopener noreferrer">
                                    <img class="contact-profile"
                                        src="<?= BASEURL . '/img/contacts/facebook-rounded-svgrepo-com.png' ?>"
                                        alt="Facebook">
                                </a>
                            <?php endif; ?>

                            <?php if (!empty($profile['tiktok'])): ?>
                                <a class="tiktok" href="<?php echo htmlspecialchars($profile['tiktok']); ?>"
                                    target="_blank" rel="noopener noreferrer">
                                    <img class="contact-profile"
                                        src="<?= BASEURL . '/img/contacts/brand-tiktok-sq-svgrepo-com.png' ?>"
                                        alt="TikTok">
                                </a>
                            <?php endif; ?>
                        </div>
                        <div class="info">
                            <h2><?php echo htmlspecialchars($profile['full_name']); ?></h2>
                            <p><?php echo htmlspecialchars($profile['position']); ?></p>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php else: ?>
                <!-- Fallback jika tidak ada data di database -->
                <div class="card">
                    <div class="info">
                        <h2>Tidak ada profil tersedia</h2>
                        <p>Silakan tambahkan profil melalui admin panel</p>
                    </div>
                </div>
            <?php endif; ?>
        </div>

        <div class="arrow arrow-right" id="arrow-right">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                <path d="M10 6L8.59 7.41 13.17 12l-4.58 4.59L10 18l6-6z" />
            </svg>
        </div>
    </div>

    <div class="slider-dots" id="slider-dots">
        <!-- Dots will be generated by JavaScript -->
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
    const slider = document.getElementById('profile-slider');
    const arrowLeft = document.getElementById('arrow-left');
    const arrowRight = document.getElementById('arrow-right');
    const dotsContainer = document.getElementById('slider-dots');
    
    if (!slider) return;
    
    const cards = slider.querySelectorAll('.card');
    const totalCards = cards.length;
    
    if (totalCards === 0) return;
    
    let currentIndex = 0;
    let cardsPerView = getCardsPerView();
    const totalPages = Math.ceil(totalCards / cardsPerView);
    
    // Fungsi untuk menentukan jumlah card yang ditampilkan berdasarkan lebar layar
    function getCardsPerView() {
        const width = window.innerWidth;
        if (width >= 1024) return 5;
        if (width >= 768) return 4;
        if (width >= 480) return 3;
        return 2;
    }
    
    // Generate dots
    function generateDots() {
        dotsContainer.innerHTML = '';
        for (let i = 0; i < totalPages; i++) {
            const dot = document.createElement('div');
            dot.classList.add('dot');
            if (i === 0) dot.classList.add('active');
            dot.addEventListener('click', () => goToSlide(i));
            dotsContainer.appendChild(dot);
        }
    }
    
    // Update dots
    function updateDots() {
        const dots = dotsContainer.querySelectorAll('.dot');
        dots.forEach((dot, index) => {
            dot.classList.toggle('active', index === currentIndex);
        });
    }
    
    // Update slider position
    function updateSlider() {
        const cardWidth = cards[0].offsetWidth;
        const gap = 15; // Sesuaikan dengan gap di CSS
        const offset = -(currentIndex * cardsPerView * (cardWidth + gap));
        slider.style.transform = `translateX(${offset}px)`;
        updateDots();
        updateArrows();
    }
    
    // Update arrow visibility
    function updateArrows() {
        arrowLeft.style.opacity = currentIndex === 0 ? '0.5' : '1';
        arrowLeft.style.cursor = currentIndex === 0 ? 'not-allowed' : 'pointer';
        
        arrowRight.style.opacity = currentIndex === totalPages - 1 ? '0.5' : '1';
        arrowRight.style.cursor = currentIndex === totalPages - 1 ? 'not-allowed' : 'pointer';
    }
    
    // Go to specific slide
    function goToSlide(index) {
        currentIndex = Math.max(0, Math.min(index, totalPages - 1));
        updateSlider();
    }
    
    // Previous slide
    function prevSlide() {
        if (currentIndex > 0) {
            currentIndex--;
            updateSlider();
        }
    }
    
    // Next slide
    function nextSlide() {
        if (currentIndex < totalPages - 1) {
            currentIndex++;
            updateSlider();
        }
    }
    
    // Event listeners
    arrowLeft.addEventListener('click', prevSlide);
    arrowRight.addEventListener('click', nextSlide);
    
    // Keyboard navigation
    document.addEventListener('keydown', function(e) {
        if (e.key === 'ArrowLeft') prevSlide();
        if (e.key === 'ArrowRight') nextSlide();
    });
    
    // Touch/swipe support
    let touchStartX = 0;
    let touchEndX = 0;
    
    slider.addEventListener('touchstart', function(e) {
        touchStartX = e.changedTouches[0].screenX;
    }, { passive: true });
    
    slider.addEventListener('touchend', function(e) {
        touchEndX = e.changedTouches[0].screenX;
        handleSwipe();
    }, { passive: true });
    
    function handleSwipe() {
        const swipeThreshold = 50;
        const diff = touchStartX - touchEndX;
        
        if (Math.abs(diff) > swipeThreshold) {
            if (diff > 0) {
                nextSlide();
            } else {
                prevSlide();
            }
        }
    }
    
    // Handle window resize
    let resizeTimer;
    window.addEventListener('resize', function() {
        clearTimeout(resizeTimer);
        resizeTimer = setTimeout(function() {
            const newCardsPerView = getCardsPerView();
            if (newCardsPerView !== cardsPerView) {
                cardsPerView = newCardsPerView;
                currentIndex = 0;
                generateDots();
                updateSlider();
            }
        }, 250);
    });
    
    // Auto-play (optional - uncomment jika ingin auto-play)
    /*
    let autoPlayInterval;
    function startAutoPlay() {
        autoPlayInterval = setInterval(function() {
            if (currentIndex < totalPages - 1) {
                nextSlide();
            } else {
                currentIndex = 0;
                updateSlider();
            }
        }, 4000); // Ganti setiap 4 detik
    }
    
    function stopAutoPlay() {
        clearInterval(autoPlayInterval);
    }
    
    // Start auto-play
    startAutoPlay();
    
    // Stop auto-play on user interaction
    slider.addEventListener('mouseenter', stopAutoPlay);
    slider.addEventListener('mouseleave', startAutoPlay);
    arrowLeft.addEventListener('click', stopAutoPlay);
    arrowRight.addEventListener('click', stopAutoPlay);
    */
    
    // Initialize
    generateDots();
    updateSlider();
});
</script>