<?php
    $youtube_title;
    $youtube_url;
    foreach ($youtube_data as $youtube_):
        if (!empty($youtube_['title']) && !empty($youtube_['url'])):
            $youtube_title = $youtube_['title'];
            $youtube_url = $youtube_['url'];
        endif;
    endforeach;
?>

<section class="video-section">
    <h1>CALENDAR OF EVENTS 2025</h1>
    <div class="video-container">
        <iframe width="560"
            height="315"
            src="<?php echo htmlspecialchars($youtube_url); ?>"
            title="<?php echo isset($youtube_title) ? htmlspecialchars($youtube_title) : 'Video Profil Tim'; ?>"
            frameborder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
            allowfullscreen>
        </iframe>
    </div>
</section>

<div class="profile-section">
    <h1>PROFIL PELIPUT PEMASARAN</h1>

    <div class="slider-container">
        <div class="arrow arrow-left" id="arrow-left">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                <path d="M15.41 7.41L14 6l-6 6 6 6 1.41-1.41L10.83 12z" />
            </svg>
        </div>

        <div class="profile-slider" id="profile-slider">
            <?php if (!empty($profiles)): ?>
                <?php foreach ($profiles as $profile): ?>
                    <div class="card">
                        <img src="<?= BASEURL . '/' . htmlspecialchars($profile['pass_photo']); ?>"
                            alt="<?php echo htmlspecialchars($profile['full_name']); ?>"
                            class="pas-photo">
                        <div class="detail">
                            <?php if (!empty($profile['linkedin'])): ?>
                                <a href="<?php echo htmlspecialchars($profile['linkedin']); ?>"
                                    target="_blank" rel="noopener noreferrer">
                                    <img class="contact-profile"
                                        src="<?= BASEURL . '/img/contacts/linkedin-rounded-svgrepo-com.png' ?>"
                                        alt="LinkedIn">
                                </a>
                            <?php endif; ?>

                            <?php if (!empty($profile['instagram'])): ?>
                                <a href="<?php echo htmlspecialchars($profile['instagram']); ?>"
                                    target="_blank" rel="noopener noreferrer">
                                    <img class="contact-profile"
                                        src="/assets/images/contacts/instagram-rounded-svgrepo-com.png"
                                        alt="Instagram">
                                </a>
                            <?php endif; ?>

                            <?php if (!empty($profile['facebook'])): ?>
                                <a href="<?php echo htmlspecialchars($profile['facebook']); ?>"
                                    target="_blank" rel="noopener noreferrer">
                                    <img class="contact-profile"
                                        src="/assets/images/contacts/facebook-rounded-svgrepo-com.png"
                                        alt="Facebook">
                                </a>
                            <?php endif; ?>

                            <?php if (!empty($profile['tiktok'])): ?>
                                <a class="tiktok" href="<?php echo htmlspecialchars($profile['tiktok']); ?>"
                                    target="_blank" rel="noopener noreferrer">
                                    <img class="contact-profile"
                                        src="/assets/images/contacts/brand-tiktok-sq-svgrepo-com.png"
                                        alt="TikTok">
                                </a>
                            <?php endif; ?>
                        </div>
                        <div class="info">
                            <h2><?php echo htmlspecialchars($profile['full_name']); ?></h2>
                            <p><?php echo htmlspecialchars($profile['position']); ?></p>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php else: ?>
                <!-- Fallback jika tidak ada data di database -->
                <div class="card">
                    <div class="info">
                        <h2>Tidak ada profil tersedia</h2>
                        <p>Silakan tambahkan profil melalui admin panel</p>
                    </div>
                </div>
            <?php endif; ?>
        </div>

        <div class="arrow arrow-right" id="arrow-right">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                <path d="M10 6L8.59 7.41 13.17 12l-4.58 4.59L10 18l6-6z" />
            </svg>
        </div>
    </div>

    <div class="slider-dots" id="slider-dots">
        <!-- Dots will be generated by JavaScript -->
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const slider = document.getElementById('profile-slider');
        const cards = slider.querySelectorAll('.card');
        const leftArrow = document.getElementById('arrow-left');
        const rightArrow = document.getElementById('arrow-right');
        const dotsContainer = document.getElementById('slider-dots');

        // Tetapkan jumlah profil per highlight menjadi 3
        const cardsPerView = 4;
        let cardWidth = cards[0].offsetWidth + 20; // Card width + gap
        let currentPosition = 0;
        let maxPosition = Math.max(0, Math.ceil(cards.length / cardsPerView) * cardsPerView - cardsPerView);

        // Create dots
        function createDots() {
            dotsContainer.innerHTML = '';
            const totalDots = Math.ceil(cards.length / cardsPerView);

            for (let i = 0; i < totalDots; i++) {
                const dot = document.createElement('div');
                dot.classList.add('dot');
                if (i === 0) dot.classList.add('active');

                dot.addEventListener('click', () => {
                    goToPosition(i * cardsPerView);
                    updateDots(i);
                });

                dotsContainer.appendChild(dot);
            }
        }

        // Update dots active state
        function updateDots(activeIndex) {
            const dots = dotsContainer.querySelectorAll('.dot');
            dots.forEach((dot, index) => {
                dot.classList.toggle('active', index === activeIndex);
            });
        }

        // Go to specific position
        function goToPosition(position) {
            position = Math.max(0, Math.min(position, maxPosition));
            currentPosition = position;
            slider.style.transform = `translateX(-${position * cardWidth}px)`;
        }

        // Create initial dots
        createDots();

        // Previous slide
        leftArrow.addEventListener('click', function () {
            if (currentPosition > 0) {
                const newPosition = currentPosition - cardsPerView;
                goToPosition(newPosition);
                updateDots(Math.floor(newPosition / cardsPerView));
            } else {
                // Loop to end if at beginning
                const newPosition = maxPosition;
                goToPosition(newPosition);
                updateDots(Math.floor(newPosition / cardsPerView));
            }
        });

        // Next slide
        rightArrow.addEventListener('click', function () {
            if (currentPosition < maxPosition) {
                const newPosition = currentPosition + cardsPerView;
                goToPosition(newPosition);
                updateDots(Math.floor(newPosition / cardsPerView));
            } else {
                // Loop to beginning if at end
                goToPosition(0);
                updateDots(0);
            }
        });

        // Handle resize
        window.addEventListener('resize', function () {
            cardWidth = cards[0].offsetWidth + 20;
            // cardsPerView tetap 3, tidak berubah saat resize
            maxPosition = Math.max(0, cards.length - cardsPerView);

            // Reset position if needed
            if (currentPosition > maxPosition) {
                currentPosition = maxPosition;
                slider.style.transform = `translateX(-${currentPosition * cardWidth}px)`;
            }
        });

        // Touch events for mobile swipe
        let touchStartX = 0;
        let touchEndX = 0;

        slider.addEventListener('touchstart', e => {
            touchStartX = e.changedTouches[0].screenX;
        });

        slider.addEventListener('touchend', e => {
            touchEndX = e.changedTouches[0].screenX;
            handleSwipe();
        });

        function handleSwipe() {
            if (touchEndX < touchStartX - 50) {
                // Swipe left - go next
                rightArrow.click();
            } else if (touchEndX > touchStartX + 50) {
                // Swipe right - go previous
                leftArrow.click();
            }
        }
    });
</script>